# Generated by Django 6.0.6 on 2026-06-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_deleted_at_member_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='kodukkan',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount to give to them', max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('given', 'MUMB KITTUVAAN - I gave them'), ('received', 'PAYATT - They gave me')], default='received', max_length=10),
        ),
    ]
