# Generated by Django 6.0.4 on 2026-06-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_remove_transaction_amount_transaction_bakki_kittan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='ippol_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
