# Generated by Django 6.0.6 on 2026-06-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_member_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
    ]
