# Generated by Django 6.0.6 on 2026-06-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_transaction_amount_alter_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='closed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('deceased', 'Deceased'), ('closed', 'Closed')], default='active', max_length=20),
        ),
    ]
